# image for building application
FROM golang:1.14-alpine as builder
# install all dependencies
RUN apk add --no-cache git make gcc g++ musl-dev linux-headers gmp-dev mpfr-dev
ADD . /bitbon-system-blockchain
RUN cd /bitbon-system-blockchain && make zksnark_generate && cd /bitbon-system-blockchain/cmd/abigen && ls -la && pwd && go build -o abigen main.go

# image for running application
FROM alpine:latest
RUN apk add --no-cache libstdc++ gmp-dev libgomp
COPY --from=builder /bitbon-system-blockchain/cmd/abigen/abigen /usr/local/bin/
RUN ln -s /usr/local/bin/abigen /abigen
EXPOSE 8545 8546 30303 30303/udp 6060
ENTRYPOINT ["/abigen"]
